<?php

namespace Slackiss\Bundle\BitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollocationRepository extends EntityRepository
{
}
