<?php

namespace Slackiss\Bundle\BitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollocationRepository extends EntityRepository
{
    public function getSelectList($current)
    {

        $collocations = $this->createQueryBuilder('a')
            ->orderBy('a.modified','desc')
            ->where('a.status = :status')
            ->andWhere('a.enabled = :enabled')
            ->andWhere('a.member = :member')
            ->setParameters(array('status'=>true,'enabled'=>true,'member'=>$current->getId()));

          return $collocations;
    }
}
