<?php

namespace Slackiss\Bundle\BitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LabelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelTypeRepository extends EntityRepository
{
}
